name: Deploy CCI Actions Demo
on:
  push:
    branches:
       master-dev
env:
  REGION_ID: cn-north-4                  # set this to your preferred huaweicloud region, e.g. cn-north-4
  ACCESS_KEY_ID: ${{ secrets.ACCESSKEY }}             # set this to your huaweicloud access-key-id
  ACCESS_KEY_SECRET: ${{ secrets.SECRETACCESSKEY }}               # set this to your huaweicloud access-key-secret
  SWR_ORGANIZATION:  demo   # SWR 组织名
  IMAGE_NAME: ccidemo       # 镜像名称
            
jobs:
  deploy_cci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Kubectl tool installer
        id: install-kubectl
        uses: Azure/setup-kubectl@v2.1

      - name: deploy to cci
        uses: ./
        id: deploy-to-cci
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          project_id: 0dd8cb413000906a2fcdc019b5a84546
          region: ${{ env.REGION_ID }}
          namespace: action-namespace
          deployment: action-deployment
          image: swr.cn-north-4.myhuaweicloud.com/hcloudcli/ccidemo:cdb1d2d867b97ea1fae088411bd73e0cc9c1dc52
